# Aalampr News Site Configuration

# Name of your site (displayed in header)
name: ஆலம்ர் செய்திகள்

# Short description shown under title or in meta tags
description: மக்கள் நலன் சார்ந்த நிகழ்வுகளை உங்களுக்காக தொகுக்கும் செய்தி தளம்

# Avatar or logo image (optional - you can update this with your real logo)
avatar: https://raw.githubusercontent.com/barryclark/jekyll-now/master/images/jekyll-logo.png

# Social Links (add only what you use)
footer-links:
  email: aalampr2025@gmail.com
  facebook: 
  instagram: 
  github: 
  twitter: 
  rss: true

# Disqus shortname for blog post comments (optional)
disqus:

# Google Analytics Tracking Code (optional)
google_analytics:

# Full site URL (you’ll use your custom domain later)
url: "https://alampr.news.io"

# If hosted on GitHub Pages project site, use baseurl (leave blank for root)
baseurl: ""

# Permalink format for posts (simplified title URLs)
permalink: /:title/

# Version of Jekyll Now used
version: v1.2.0

# Markdown parser settings
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'

# SCSS options
sass:
  style: :expanded

# Plugins
gems:
  - jekyll-sitemap
  - jekyll-feed

# Files to exclude from the generated site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
